### ISSUE TITLE
Auto Pair Issue

### ISSUE THREAD

**Issue by kshitijvyas123** [status-im/status-keycard#53] opened 2019-08-20 08:12 UTC
Hello,
Trying to use the code with my status keycard(It is black,).
I am able to fetch the info from it
08-20 15:21:41.542 9643-9663/im.status.keycard.demo I/MainActivity: Instance UID: 8c82bedc0b65b9d75d5a9b6b29ee52d8
08-20 15:21:41.542 9643-9663/im.status.keycard.demo I/MainActivity: Secure channel public key: 04187e3f406db8852fae444b635949e09140a556af6ef8ed0a7163ce0f01ad5d85be96f746a1cd2a2a21c90907eebd4cf99649b09969fc0514fefbd09a5143978c
08-20 15:21:41.542 9643-9663/im.status.keycard.demo I/MainActivity: Application version: 2.1
08-20 15:21:41.542 9643-9663/im.status.keycard.demo I/MainActivity: Free pairing slots: 0
08-20 15:21:41.542 9643-9663/im.status.keycard.demo I/MainActivity: Key UID: 654cd70200be6f694a1ff76dce94b446cfb48543bae855419519ed9cb4459aa6
08-20 15:21:41.542 9643-9663/im.status.keycard.demo I/MainActivity: Capabilities: 0F
08-20 15:21:41.543 9643-9663/im.status.keycard.demo I/MainActivity: Has Secure Channel: true
08-20 15:21:41.543 9643-9663/im.status.keycard.demo I/MainActivity: Has Key Management: true
08-20 15:21:41.543 9643-9663/im.status.keycard.demo I/MainActivity: Has Credentials Management: true
08-20 15:21:41.543 9643-9663/im.status.keycard.demo I/MainActivity: Has NDEF capability: true
08-20 15:21:41.543 9643-9663/im.status.keycard.demo I/MainActivity: Has cmdh: 0
08-20 15:21:41.543 9643-9663/im.status.keycard.demo D/CardChannel: COMMAND CLA: 80 INS: 20 P1: 00 P2: 00 LC: 06
08-20 15:21:41.629 9643-9663/im.status.keycard.demo D/CardChannel: RESPONSE LEN: 00, SW: 6985
But when I am trying to call cmdSet.verifyPin("000000");

I am getting below error:

08-20 15:21:41.630 9643-9663/im.status.keycard.demo W/System.err: im.status.keycard.io.APDUException: SW_CONDITIONS_OF_USE_NOT_SATISFIED, 0x6985
08-20 15:21:41.630 9643-9663/im.status.keycard.demo W/System.err: at im.status.keycard.io.APDUResponse.checkSW(APDUResponse.java:91)
08-20 15:21:41.630 9643-9663/im.status.keycard.demo W/System.err: at im.status.keycard.io.APDUResponse.checkOK(APDUResponse.java:64)
08-20 15:21:41.630 9643-9663/im.status.keycard.demo W/System.err: at im.status.keycard.io.APDUResponse.checkAuthOK(APDUResponse.java:109)
08-20 15:21:41.630 9643-9663/im.status.keycard.demo W/System.err: at im.status.keycard.app.MainActivity$1.onConnected(MainActivity.java:74)
08-20 15:21:41.630 9643-9663/im.status.keycard.demo W/System.err: at im.status.keycard.android.NFCCardManager.onCardConnected(NFCCardManager.java:97)
08-20 15:21:41.630 9643-9663/im.status.keycard.demo W/System.err: at im.status.keycard.android.NFCCardManager.run(NFCCardManager.java:80)
08-20 15:21:41.630 9643-9663/im.status.keycard.demo E/MainActivity: SW_CONDITIONS_OF_USE_NOT_SATISFIED, 0x6985

Also when I am calling cmdSet.autoPair("KeycardTest");
It gives me IO Exception.
Any thing which I am missing. Or I need to format the card and then intialize everything again

**Comment by bitgamma** [comment] 2019-08-20 08:37
duplicate of https://github.com/status-im/status-keycard-java/issues/17

**Closed by bitgamma** 2019-08-20 08:37 UTC
